
service: reactive-quizlet-server

provider:
  name: aws
  runtime: nodejs6.10
  profile: reactive
  region: us-east-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: arn:aws:dynamodb:us-east-2:*:*

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

custom:
  dotenv:
    path: configs/.env
    include:
      - AWS_USER_ARN
  webpack: ./webpack.config.js
  webpackIncludeModules: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello

  graphql:
      handler: src/handler.graphqlHandler
      events:
      - http:
          path: graphql
          method: post
          cors: true

  playground:
    handler: src/handler.playgroundHandler
    events:
    - http:
        path: playground
        method: get
        cors: true

  graphiql:
    handler: src/handler.graphiqlHandler
    events:
    - http:
        path: graphiql
        method: get
        cors: true

# if tables do not exist
#resources:
#   Resources:
#      DynamoDBSets:
#        Type: 'AWS::DynamoDB::Table'
#        Properties:
#          AttributeDefinitions:
#            - AttributeName: id
#              AttributeType: S
#          KeySchema:
#            - AttributeName: id
#              KeyType: HASH
#          TableName: sets
#          ProvisionedThroughput:
#            ReadCapacityUnits: 5
#            WriteCapacityUnits: 5
#
#      DynamoDBCards:
#        Type: 'AWS::DynamoDB::Table'
#        Properties:
#          AttributeDefinitions:
#            - AttributeName: id
#              AttributeType: S
#          KeySchema:
#            - AttributeName: id
#              KeyType: HASH
#          TableName: cards
#          ProvisionedThroughput:
#            ReadCapacityUnits: 5
#            WriteCapacityUnits: 5
